graph TD
    subgraph Data Substitution
    parta[part_1]
    partb[part_2]
    partc[part_3]
    partd[part_4]
    parta -.-> vara[  A = part_1]
    partb -.-> varb[  B = part_2]
    partc -.-> varc[  C = part_3] 
    partd -.-> vard[  D = part_4]
    end
    subgraph Create equations with the data parts 
    eq1[A + B + C + D = 6]
    eq2[A +  B +  C -  D = 3]
    eq3[A +  B -  C -  D = 10]
    eq4[ A -  B -  C -  D = -4]
    eq5[ A -  B +  C +  D = 0]
    eq6[ A -  B -  C +  D = 5]
    vara & varb & varc & vard --> eq1 & eq2 & eq3 & eq4 & eq5 & eq6
    end