graph TD
    subgraph Data Origin
    file[Large chunk of data =  part_1part_2part_3part_4]
    parta[part_1]
    partb[part_2]
    partc[part_3]
    partd[part_4]
    file -.- |split part_1|parta
    file -.- |split part_2|partb
    file -.- |split part 3|partc
    file -.- |split part 4|partd
    parta --> partb --> partc --> partd
    end